name: CD

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.100

    - name: Pack
      run: |
        dotnet build --configuration Release
        dotnet pack Onova --configuration Release --no-build

    - name: Deploy
      run: dotnet nuget push Onova\bin\Release\*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
